info:
  contact: {}
  description: Fast and modern REST-API for Swiss Postal Codes
  title: Postal Codes API
  version: "1.0"
paths:
  /api/plz/all:
    get:
      consumes:
      - application/json
      description: Get all Postal Codes
      produces:
      - application/json
      responses: {}
      summary: Get all Postal Codes
      tags:
      - postal-codes
  /api/plz/search:
    get:
      consumes:
      - application/json
      description: Returns a list of postal codes based on the query.
      parameters:
      - description: plz search by place
        in: query
        name: place
        type: string
      - description: plz search by code
        in: query
        name: code
        type: string
      produces:
      - application/json
      responses: {}
      summary: Finds Postal Codes
      tags:
      - postal-codes
swagger: "2.0"
